import { filesSnapshot, inputVideoPathValue, mediaManifestSnapshot, outputPathValue } from "./media-state.js";
import { state } from "./state.js";
import { getAppState, normalizeSubtitleMode, normalizeWorkflowSection, patchAppState } from "./store/app-store.js";

export function syncAppStoreFromLegacyState() {
	patchAppState({
		env: state.env,
		project: state.project,
		projectStatePath: state.projectStatePath,
		projectStateRevision: state.projectStateRevision,
		projectStateApplying: state.projectStateApplying,
		projectStatePersistTimer: state.projectStatePersistTimer,
		projectList: state.projectList,
		projectListLoading: state.projectListLoading,
		mediaManifest: mediaManifestSnapshot(),
		mediaDirectory: state.mediaDirectory,
		materialPaths: [...state.materialPaths],
		materialSourcePreviews: [...state.materialSourcePreviews],
		materialSourcePreviewLoading: state.materialSourcePreviewLoading,
		materialSourcePreviewRequestId: state.materialSourcePreviewRequestId,
		materialAnalysisCancelable: state.materialAnalysisCancelable,
		materialAnalysisCancelRequested: state.materialAnalysisCancelRequested,
		fullAnalysisRunning: state.fullAnalysisRunning,
		ingestRunning: state.ingestRunning,
		ingestProgress: state.ingestProgress,
		runningAction: state.directRunRunning ? state.runningAction : "",
		lastWorkflowProgressLog: state.lastWorkflowProgressLog,
		lastWorkflowStage: state.lastWorkflowStage,
		appLocked: state.appLocked,
		appBusyTitle: state.appBusyTitle,
		appBusyMessage: state.appBusyMessage,
		analysisResults: state.analysisResults.map((item) => ({ ...item })),
		analysisTitleText: state.analysisTitleText,
		files: filesSnapshot(),
		subtitleMode: normalizeSubtitleMode(state.subtitleMode),
		syncReport: state.syncReport,
		glossaryTerms: state.glossaryTerms,
		outputPreview: state.outputPreview,
		outputPreviewKind: state.outputPreviewKind,
		outputPreviewLoading: state.outputPreviewLoading,
		punchlineText: getAppState().punchlineText,
		inputVideoPath: inputVideoPathValue(),
		outputPath: outputPathValue(),
		filePreviews: { ...state.filePreviews },
		codexModels: state.codexModels,
		codexModelsLoading: getAppState().codexModelsLoading,
		codexModel: state.codexModel,
		codexModelStatusKey: state.codexModelStatusKey,
		codexModelStatusValues: state.codexModelStatusValues,
		activeSection: normalizeWorkflowSection(state.activeSection),
		language: state.language,
		statusText: state.statusText,
		statusKind: state.statusKind,
		directRunRunning: state.directRunRunning,
		codexTurnRunning: state.codexTurnRunning,
		codexInterruptRequested: state.codexInterruptRequested,
	});
}
