from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from project_paths import (
    CONFIG,
    OUTPUT_DIAGNOSTICS,
    OUTPUT_OVERLAYS,
    OUTPUT_REPORTS,
    OUTPUT_TRANSCRIPTS,
    OUTPUT_VIDEOS,
    ROOT as WORKSPACE_ROOT,
    SCRIPTS,
    SOURCE_AUDIO,
    SOURCE_IMAGES,
    SOURCE_SUBTITLES,
    SOURCE_VIDEO,
    multicam_source_root,
    resolve_project_path,
)

from PIL import ImageFont


WORK = WORKSPACE_ROOT
FONT_PATH = Path(r"C:\Windows\Fonts\YuGothB.ttc")
OUTPUT = OUTPUT_OVERLAYS / "punchline_subtitles.ass"


@dataclass(frozen=True)
class Punchline:
    start: str
    end: str
    lines: tuple[str, ...]


PUNCHLINES = [
    Punchline("0:00:00.00", "0:00:04.00", ("定義で言うと強いプロダクトというか", "プロダクトが中心にあって")),
    Punchline("0:00:09.00", "0:00:13.00", ("届けるというところだと思っているので",)),
    Punchline("0:00:15.00", "0:00:20.00", ("そこで一定なスケルメリットが", "出るということが大事だと思いますね")),
    Punchline("0:01:11.00", "0:01:13.00", ("過剰反応されてるだけな気がしますけどね",)),
    Punchline("0:01:27.00", "0:01:33.00", ("さすがに薄々AIによって", "何かが変わるなっていうのは")),
    Punchline("0:01:37.00", "0:01:41.00", ("どうなるんだろうっていう", "漠然とした不安がある中で")),
    Punchline("0:01:56.00", "0:02:02.00", ("あなたの仕事例えばライターの仕事", "明日から亡くなりますよって言われたら")),
    Punchline("0:02:17.00", "0:02:24.00", ("会社がわざわざ", "PDM配信してフリーEにしましたみたいなのは")),
    Punchline("0:02:24.00", "0:02:29.00", ("基本的な採用候補というか", "採用におけるマーケティングの一環なのかなと思いますね")),
    Punchline("0:02:29.00", "0:02:37.00", ("同じような職種名だと埋もれるんで", "興味持ってもらうっていうのは")),
    Punchline("0:03:01.00", "0:03:07.00", ("採用救人状の話だったけで", "家事ある面談とか面接を通して")),
    Punchline("0:03:07.00", "0:03:13.00", ("なるほどこういう役割を求めてるの", "すり合うパターンもあるかもしれないし")),
    Punchline("0:03:41.00", "0:03:49.00", ("会社によってビジネスのモデルとか", "通用見とかっていうのは", "かなり多種多様なんですよね")),
    Punchline("0:03:57.00", "0:04:04.00", ("各会社さんとかの", "勝ち方というか")),
    Punchline("0:04:06.00", "0:04:13.00", ("なんでユーザーさんに必要されているか", "みたいなところって", "多様性もあるし")),
    Punchline("0:04:25.00", "0:04:35.00", ("大まかな専門職的な", "この仕事が必要というのは", "もちろんありますと")),
    Punchline("0:04:40.00", "0:04:46.00", ("専門職という言葉が", "結構ミスリートというか", "エンジニアとか")),
    Punchline("0:04:46.00", "0:04:51.00", ("分かりやすすぎるだけなんですよね", "話として")),
]


def font_size_for(lines: tuple[str, ...]) -> int:
    longest = max(len(line) for line in lines)
    if len(lines) >= 3:
        return 98 if longest <= 20 else 90
    if longest >= 31:
        return 94
    if longest >= 25:
        return 108
    return 116


def line_size(line: str, font_size: int) -> tuple[int, int]:
    font = ImageFont.truetype(str(FONT_PATH), font_size, index=1)
    left, top, right, bottom = font.getbbox(line)
    return right - left, bottom - top


def line_box_geometry(lines: tuple[str, ...]) -> tuple[int, list[tuple[str, int, int, int, int]]]:
    font_size = font_size_for(lines)
    pad_x = 2
    pad_y = 2
    gap = 0
    boxes: list[tuple[str, int, int, int, int]] = []
    heights: list[int] = []
    widths: list[int] = []
    for line in lines:
        text_width, text_height = line_size(line, font_size)
        widths.append(min(1760, text_width + pad_x * 2))
        heights.append(max(text_height + pad_y * 2, int(font_size * 1.02)))
    total_height = sum(heights) + gap * (len(lines) - 1)
    y = 1080 - 36 - total_height
    for line, width, height in zip(lines, widths, heights):
        x = round((1920 - width) / 2)
        boxes.append((line, x, y, width, height))
        y += height + gap
    return font_size, boxes


def ass_text(lines: tuple[str, ...]) -> str:
    return r"\N".join(lines)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    header = """[Script Info]
; Punchline-only subtitles. Text must be copied from the original SRT, not summarized.
; Generated by generate_punchline_subtitles.py.
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: PunchShadow,Arial,1,&H000000D8,&H000000D8,&H000000D8,&H000000D8,0,0,0,0,100,100,0,0,1,0,0,7,0,0,0,1
Style: PunchBox,Arial,1,&H00FFFFFF,&H00FFFFFF,&H00FFFFFF,&H00FFFFFF,0,0,0,0,100,100,0,0,1,0,0,7,0,0,0,1
Style: PunchText,Yu Gothic UI Semibold,116,&H000000D8,&H000000FF,&H000000D8,&H000000D8,1,0,0,0,100,100,0,0,1,1.2,0,5,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    events: list[str] = []
    for item in PUNCHLINES:
        font_size, boxes = line_box_geometry(item.lines)
        for line, x, y, width, height in boxes:
            shadow_x = x + 12
            shadow_y = y + 12
            center_y = y + height / 2
            start_y = center_y + 44
            events.extend(
                [
                    f"Dialogue: 9,{item.start},{item.end},PunchShadow,,0,0,0,,"
                    f"{{\\fad(160,180)\\move({shadow_x},{shadow_y + 44},{shadow_x},{shadow_y},0,260)\\p1}}"
                    f"m 0 0 l {width} 0 l {width} {height} l 0 {height}",
                    f"Dialogue: 10,{item.start},{item.end},PunchBox,,0,0,0,,"
                    f"{{\\fad(160,180)\\move({x},{y + 44},{x},{y},0,260)\\p1}}"
                    f"m 0 0 l {width} 0 l {width} {height} l 0 {height}",
                    f"Dialogue: 11,{item.start},{item.end},PunchText,,0,0,0,,"
                    f"{{\\fad(160,180)\\move(960,{start_y:.0f},960,{center_y:.0f},0,260)"
                    f"\\fscx88\\fscy88\\t(0,220,\\fscx100\\fscy100)\\fs{font_size}}}"
                    f"{line}",
                ]
            )
    OUTPUT.write_text(header + "\n".join(events) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
